trigger:
- main

pool:
 name: Local

variables:
  buildConfiguration: 'Release'
  
steps:
# Install
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 8.x

# Restore
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    arguments: --force
    feedsToUse: 'select'
    vstsFeed: 'geekymon2'

# Build
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

# Archive the build output
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/build_output.zip'
    verbose: true

# Publish the zip file as a universal package to Azure Artifacts
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: 'Tasker/tasker'
    versionOption: 'custom'
    versionPublish: '$(Build.BuildId)'
    packagePublishDescription: 'Build output as a zip file'
