trigger:
- main

pool:
 name: Local

variables:
  buildConfiguration: 'Release'
  
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 8.x
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    arguments: --force
    feedsToUse: 'select'
    vstsFeed: 'geekymon2'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'
